<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\MyPowerTools.Abstractions\MyPowerTools.Abstractions.csproj" />
    <ProjectReference Include="..\MyPowerTools.Protocol\MyPowerTools.Protocol.csproj" />
    <ProjectReference Include="..\MyPowerTools.Platform.Abstractions\MyPowerTools.Platform.Abstractions.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ModulePackageRoot>$(MSBuildProjectDirectory)\..\..\modules\screenease</ModulePackageRoot>
  </PropertyGroup>

  <Target Name="CopyModuleAssemblyToPackage" AfterTargets="Build">
    <ItemGroup>
      <ModuleDependencyFiles Include="$(TargetDir)MyPowerTools.Platform.Abstractions.dll" />
      <ModuleDependencyFiles Include="$(TargetDir)MyPowerTools.Platform.Abstractions.pdb" />
    </ItemGroup>
    <MakeDir Directories="$(ModulePackageRoot)" />
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(ModulePackageRoot)" />
    <Copy SourceFiles="$(TargetDir)$(TargetName).pdb" DestinationFolder="$(ModulePackageRoot)" Condition="Exists('$(TargetDir)$(TargetName).pdb')" />
    <Copy SourceFiles="@(ModuleDependencyFiles)" DestinationFolder="$(ModulePackageRoot)" SkipUnchangedFiles="true" />
  </Target>

</Project>
