<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>ScreenEase.Surface</AssemblyName>
    <RootNamespace>ScreenEase.Surface</RootNamespace>
    <IsPackable>true</IsPackable>
    <PackageId>ScreenEase.Surface</PackageId>
    <Version>0.2.0</Version>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.0.5" />
    <PackageReference Include="MyPowerTools.ToolSdk" Version="0.2.0" />
    <PackageReference Include="MyPowerTools.AvaloniaSdk" Version="0.2.0" />
    <PackageReference Include="MyPowerTools.UI" Version="0.2.0" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="MyPowerTools.Tests" />
  </ItemGroup>
</Project>
